### ISSUE TITLE
[BUG] default value only one replace

### ISSUE THREAD

**Issue by chiol** [vara855/yaml-env-defaults#17]
**Describe the bug**
Two or more default values in one line are not worked.

**To Reproduce**
```
mysql:
  url: mysql://${MYSQL_USER:root}:${MYSQL_PASSWORD:password}@${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:feedback_1}
```
Result
```
mysql:
    url: mysql://${MYSQL_USER:root}:${MYSQL_PASSWORD:password}@${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/feedback_1
```

Expected
```
mysql:
    url: mysql://root:password@localhost:3306/feedback_1
```

**Comment by vara855** [comment]
@chiol  Hi! Thank you for bug report. I've fixed it. Please update to [2.0.2](https://www.npmjs.com/package/yaml-env-defaults/v/2.0.2) or [1.6.1](https://www.npmjs.com/package/yaml-env-defaults/v/1.1.6)
