### ISSUE TITLE
[BUG] readYamlEnvSync error without pass the second parameter

### ISSUE THREAD

**Issue by ellencheung39** [vara855/yaml-env-defaults#3]
**Describe the bug**
try to use process.env to parse yaml
throw error without pass function in the second parameter

**To Reproduce**
1. YAML file(s)
  test: ${TEST}
2. Code 
  process.env.TEST = "test"
  readYamlEnvSync(--path-to-yaml)
**Expected behavior**
parse successfully and return { test: "test" }

**Screenshots**
![image](https://user-images.githubusercontent.com/20609379/170908163-ff0f61e3-fd3c-4512-9829-4b269ec0eae5.png)
should update envVarValue instead of envVarName 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Node.js: v16.13.2
 - Version: 1.1.3

**Comment by vara855** [comment]
Hi @ellencheung39 . Thank you for issue. I've wrote test for your case & I don't have any problems with that
https://github.com/vara855/yaml-env-defaults/pull/4/files#diff-5004cb2a053a1a46d00bbea1bd77addc85e93cc6e8df5ba4dc04fed6d5a3ca9eR176 

Could you maybe reproduce that in some sandbox environment?

**Comment by ellencheung39** [comment]
I found that the compiled files is different with those installed by npm

![image](https://user-images.githubusercontent.com/20609379/172556859-27ae4315-54c5-491c-bb57-56c8104d2b98.png)

Maybe this is bug on npm instead of your package.

**Comment by chris-lee-lb** [comment]
I also faced this problem too ... really weird bug by npm ...

<img width="973" alt="截圖 2022-08-20 下午4 18 38" src="https://user-images.githubusercontent.com/83692195/185736006-5af13f38-9143-4b39-8eb7-129859f6f125.png">

This is screenshot from `node_modules/yaml-env-defaults/lib/read-yaml-config.js`

And you can see that `envVarName = mergedValues[envVarName];` which should be `envVarValue = mergedValues[envVarName];`

**Comment by vara855** [comment]
@chris-lee-lb  & @ellencheung39 Yes, you're right. Please check the latest version 1.1.5 or 2.0.1
